# Generated by Django 3.1.3 on 2020-12-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Remera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=128)),
                ('talle', models.IntegerField()),
                ('color', models.CharField(max_length=128)),
                ('lisa', models.BooleanField()),
                ('genero', models.IntegerField()),
            ],
        ),
    ]
