# Generated by Django 3.1.3 on 2020-12-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remera',
            name='color',
            field=models.CharField(max_length=128, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='remera',
            name='genero',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Hombre'), (2, 'Mujer'), (3, 'Unisex')], verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='remera',
            name='lisa',
            field=models.BooleanField(verbose_name='Lisa'),
        ),
        migrations.AlterField(
            model_name='remera',
            name='marca',
            field=models.CharField(max_length=128, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='remera',
            name='talle',
            field=models.PositiveSmallIntegerField(choices=[(1, 'XS'), (2, 'S'), (3, 'M'), (4, 'L'), (5, 'XL'), (6, 'XXL')], verbose_name='Talle'),
        ),
    ]
