# Generated by Django 3.1.3 on 2020-12-22 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201216_1459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remera',
            options={'ordering': ['marca'], 'verbose_name': 'Remera', 'verbose_name_plural': 'Remeras'},
        ),
    ]
